# Generated by Django 4.2.11 on 2024-04-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_thumbnail_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='uri',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
